// This file is auto-generated by @hey-api/openapi-ts

export type PostReadable = {
    id?: number;
    title: string;
    content?: string;
    readonly author?: string;
    tags?: Array<string>;
    createdAt?: string;
    updatedAt?: string;
};

export type PostWritable = {
    id?: number;
    title: string;
    content?: string;
    tags?: Array<string>;
    createdAt?: string;
    updatedAt?: string;
};

export type Participant = {
    email: string;
    response?: 'accepted' | 'declined';
};

export type Jam = {
    id: number;
    name: string;
    startTimestampSeconds: number;
    endTimestampSeconds: number;
    location: string;
    createdBy: string;
    participants: Array<Participant>;
};

export type CreateJamRequest = {
    name: string;
    startTimestampSeconds: number;
    endTimestampSeconds: number;
    location: string;
    participants: Array<Participant>;
};

export type GetPostsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/posts';
};

export type GetPostsResponses = {
    /**
     * OK
     */
    200: Array<PostReadable>;
};

export type GetPostsResponse = GetPostsResponses[keyof GetPostsResponses];

export type CreatePostData = {
    body: PostWritable;
    path?: never;
    query?: never;
    url: '/api/v1/posts';
};

export type CreatePostResponses = {
    /**
     * Created
     */
    201: {
        id: number;
    };
};

export type CreatePostResponse = CreatePostResponses[keyof CreatePostResponses];

export type DeletePostData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/v1/posts/{id}';
};

export type DeletePostResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeletePostResponse = DeletePostResponses[keyof DeletePostResponses];

export type GetPostData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/v1/posts/{id}';
};

export type GetPostResponses = {
    /**
     * OK
     */
    200: PostReadable;
};

export type GetPostResponse = GetPostResponses[keyof GetPostResponses];

export type UpdatePostData = {
    body: PostWritable;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/v1/posts/{id}';
};

export type UpdatePostResponses = {
    /**
     * OK
     */
    200: PostReadable;
};

export type UpdatePostResponse = UpdatePostResponses[keyof UpdatePostResponses];

export type GetJamsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/jams';
};

export type GetJamsErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
};

export type GetJamsResponses = {
    /**
     * OK
     */
    200: Array<Jam>;
};

export type GetJamsResponse = GetJamsResponses[keyof GetJamsResponses];

export type CreateJamData = {
    body: CreateJamRequest;
    path?: never;
    query?: never;
    url: '/api/v1/jams';
};

export type CreateJamErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
};

export type CreateJamResponses = {
    /**
     * Created
     */
    201: {
        id: number;
    };
};

export type CreateJamResponse = CreateJamResponses[keyof CreateJamResponses];

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};